---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-runtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-runtime
  template:
    metadata:
      labels:
        app: redis-runtime
    spec:
      containers:
      - name: redis-runtime
        image: ghcr.io/luiz-couto/redis-runtime:v0.0.1 
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        volumeMounts:
        - name: pyfile
          mountPath: "/app/usermodule.py"
          subPath: "pyfile"
        env:
        - name: REDIS_HOST
          value: "192.168.121.189"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_INPUT_KEY
          value: "metrics"
        - name: REDIS_OUTPUT_KEY
          valueFrom:
            configMapKeyRef:
              name: outputkey
              key: REDIS_OUTPUT_KEY
      volumes:
      - name: pyfile
        configMap:
          name: pyfile